repos:
-   repo: local
    hooks:
    -   id: pytest
        name: 'pytest'
        entry: /usr/bin/env sh -c "DO_NOT_SHOW_PLOTS=1 poetry run pytest --disable-warnings"
        language: script
        always_run: true
        pass_filenames: false
