site_name: Soldat2 stats
site_url: https://s2vndl.github.io/s2stats/docs/
theme: readthedocs
docs_dir: build/markdown
site_dir: docs
nav:
  - index.md
  - stats_weapon_win_correlation_info.md
  - stats_weapon_win_correlation_ranked.md
  - stats_weapon_win_correlation_wm.md
  - stats_weapon_win_correlation_wm_previous.md
  - stats_maps_trends.md
  - stats_weapon_usage_trends_v2.md
  - stats_weapon_usage_trends.md
  - stats_ranked.md
  - stats_tournament.md