#!/usr/bin/env bash
set -o errexit

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR"

rm -rf build
rm -rf docs
mkdir -p build/markdown/data
mkdir -p build/data
mkdir -p build/notebooks
mkdir -p docs
cp README.md build/markdown/index.md

python3 -m venv venv
source venv/bin/activate
python -m pip install -qr requirements.txt
ls *.ipynb | xargs -I I papermill --no-progress-bar --log-level ERROR I build/notebooks/I
jupyter nbconvert --to markdown --output-dir=build/markdown build/notebooks/*.ipynb --no-input --log-level ERROR

mkdocs build | grep -V INFO
