#!/usr/bin/env bash
set -o errexit

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR"

rm -rf build
rm -rf docs
mkdir -p build/markdown/data
mkdir -p build/data
mkdir -p build/notebooks
mkdir -p docs
cp README.md build/markdown/index.md

poetry install
ls *.ipynb | xargs -I QQ poetry run papermill --log-level WARNING --execution-timeout 20 QQ build/notebooks/QQ
poetry run jupyter nbconvert --to markdown --output-dir=build/markdown build/notebooks/*.ipynb --no-input --log-level ERROR

poetry run mkdocs build 2> >(grep -ive '^INFO' >&2)
