#!/usr/bin/env bash
set -o errexit
set -o xtrace

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR"
python3 -m venv venv
source venv/bin/activate
which python
python -vm pip install -r requirements.txt
ls *.ipynb | xargs -I I papermill I I
